apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  namespace: fraud-detection
  labels:
    app: fraud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: fraud-api
          image: ghcr.io/eugenepanfilov/otus-model-as-a-service-k8s:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: fraud-api-config
            - secretRef:
                name: fraud-api-secret

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"